/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[PropertyTypeId]
      ,[AddressId]
      ,[Name]
      ,[Description]
      ,[Bedroom]
      ,[Bathroom]
      ,[LandSqm]
      ,[ParkingSpace]
      ,[FloorArea]
      ,[TargetRent]
      ,[TargetRentTypeId]
      ,[YearBuilt]
      ,[IsActive]
      ,[CreatedOn]
      ,[CreatedBy]
      ,[UpdatedOn]
      ,[UpdatedBy]
      ,[HasCompany]
      ,[IsOwnerOccupied]
  FROM [Keys].[dbo].[Property]